


export const Products = [
    {
      id: 1,
      productName: 'Self Propel Power Reapear',
      Price: 10000,
      productImage: '/Assets/walk.jpeg',
      productDescription: 'Self propelled reaper is self propelled one used to harvest multiple crops like paddy, wheat. red gram, black gram, bengal gram and many crops.',
      category: 'Farm Equipment',
    },
    {
      id: 2,
      productName: 'Advanced Tractor 2000',
      Price: 160000,
      productImage: '/Assets/tractor.png',
      productDescription: 'Boost your farming efficiency with ',
      category: 'Farm Equipment',
    },
    {
      id: 3,
      productName: 'Heavy-duty Crane',
      Price: 120999,
      productImage: '/Assets/fan.jpeg',
      productDescription: 'Handle heavy lifting with ease.',
      category: 'Construction',
    },
    {
      id: 4,
      productName: 'Water Pump Set Diesel',
      Price: 6000,
      productImage: '/Assets/pump.png',
      productDescription: 'A water pump is a machine that is used to transfer water from one location to another. ',
      category: 'General',
    },
    {
      id: 5,
      productName: 'Innovative ABC Gadget',
      Price: 6000,
      productImage: '/Assets/tractorblue.jpeg',
      productDescription: 'Stay ahead with our ',
      category: 'Farm Equipment',
    },
    {
      id: 6,
      productName: 'Sweet Watermelon',
      Price: 6000,
      productImage: '/Assets/product4.jpeg',
      productDescription: 'Enjoy the sweetness .',
      category: 'Fruits',
    },
    {
      id: 7,
      productName: 'Eco-friendly XYZ Product',
      Price: 6000,
      productImage: '/Assets/cutting.png',
      productDescription: 'Embrace sustainability ',
      category: 'Sustainable Living',
    },
    {
      id: 8,
      productName: 'Smartphone XYZ',
      Price: 10000,
      productImage: '/Assets/fartilizer1.jpeg',
      productDescription: 'Experience the latest in mobile ',
      category: 'Electronics',
    },
    {
      id: 9,
      productName: 'Mini Tractor 2000',
      Price: 160000,
      productImage: '/Assets/minitractor.jpeg',
      productDescription: 'Boost your farming efficiency with ',
      category: 'Farm Equipment',
    },
    {
      id: 10,
      productName: 'Hand Gloves',
      Price: 120999,
      productImage: '/Assets/gloves.jpeg',
      productDescription: 'Handle heavy lifting with ease.',
      category: 'Construction',
    },
    {
      id: 11,
      productName: 'Premium XYZ Product',
      Price: 6000,
      productImage: '/Assets/walk.jpeg',
      productDescription: 'Discover excellence with our . ',
      category: 'General',
    },
    {
      id: 12,
      productName: 'Innovative ABC Gadget',
      Price: 6000,
      productImage: '/Assets/fartilizer.jpeg',
      productDescription: 'Stay ahead with our ',
      category: 'Gadgets',
    },
    {
      id: 13,
      productName: 'Rice Cutter',
      Price: 6000,
      productImage: '/Assets/rice.jpeg',
      productDescription: 'Enjoy the sweetness .',
      category: 'Fruits',
    },
    {
      id: 14,
      productName: 'Eco-friendly Fan',
      Price: 6000,
      productImage: '/Assets/fan.jpeg',
      productDescription: 'Embrace sustainability ',
      category: 'Sustainable Living',
    },
  ];
  